### ISSUE TITLE
FR: lock orientation when going fullscreen

### ISSUE THREAD

**Issue by mounirlamouri** [GoogleChrome/sample-media-pwa#1]
It would be great if the feature implemented by Chrome for the native controls could be implemented in the sample: when a video goes fullscreen, the orientation is locked to match the video's aspect ratio (maybe only landscape in your case?). If you like to read C++, you can check the [Blink's implementation](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/html/shadow/MediaControlsOrientationLockDelegate.cpp). Most of it should translate to Javascript fairly well.

**Comment by paullewis** [comment]
Fixed in 2bce6290b4f313fcf03efe1afacc13d052355a3e
