### ISSUE TITLE
hash-removal.js "hasHashInName" never checks if actual hash in url

### ISSUE THREAD

**Issue by wasdennnoch** [GoogleChrome/sample-media-pwa#14]
Minor thing I noticed, in the [hash-removal.js](https://github.com/GoogleChrome/sample-media-pwa/blob/master/src/server/middleware/hash-removal.js) the constant `hasHashInName` gets initialized with the regex and then `if (!hasHashInName)` gets tested. This doesn't make sense since the actual url never gets checked against the regex and the hash always gets removed. It only works because if there's no hash nothing gets removed. Not a big issue but a bit confusing ;)

**Comment by paullewis** [comment]
Thanks!
