### ISSUE TITLE
PWA doesn't degrade gracefully on browsers that don't support service workers

### ISSUE THREAD

**Issue by hbengali** [GoogleChrome/sample-media-pwa#17]
We should be degrading gracefully on browsers that don't support service workers. Right now, in Safari on desktop (and Chrome/Safari on iOS), the thumbnails for the images do not show up, and the videos do not play.

**Comment by paullewis** [comment]
Absolutely! It _did_ work so this is a recent issue, I suspect. I'll look into it.

**Comment by paullewis** [comment]
This is now fixed and deployed. However _some_ videos aren't quite working yet, simply because some changes still seem to be propagating out.

**Comment by paullewis** [comment]
I'll hold closing this until I can confirm everything is as expected.

**Comment by hbengali** [comment]
Thanks for the rapid turn around!
