### ISSUE TITLE
Text spacing is odd

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/sample-media-pwa#2]
![image](https://cloud.githubusercontent.com/assets/205226/22704656/605118f0-ed60-11e6-8a1c-dde0fc321faf.png)

`<p>All our content is available on the web, which means you can getaccess to it whenever you want it. What’s more, if your browsersupports the latest technologies, you can save videos to viewwhenever you’re offline!</p>
`

**Comment by paullewis** [comment]
Fixed.
