### ISSUE TITLE
Nit

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/sample-media-pwa#6]
In https://github.com/GoogleChrome/sample-media-pwa/blob/2efbd1e25d1919c78eecb997318bfaaaf5e8ae7e/src/client/scripts/video-player/video-player.js#L175, did you mean `SUPPORTS_REMOTE_PLAYBACK` instead of `SUPPORTS_MEDIA_SESSION`?

@paullewis

**Comment by paullewis** [comment]
I really truly did.

**Comment by paullewis** [comment]
Fixed
