### ISSUE TITLE
Feature request: Tests!

### ISSUE THREAD

**Issue by gpolyn** [GoogleChrome/sample-media-pwa#8]
Gee, where are the tests?

**Comment by paullewis** [comment]
👍 Great question. I'll be honest, I've never figured out how to genuinely test UI work well. Do you have experience with it?

**Comment by gpolyn** [comment]
@PaulKinlan, no, I have no experience.

I note Google's firm advocacy of PWA, while puzzled at the omission of this topic in that advocacy.

Just thought I'd present this feature request, as this repo seems an authoritative source, right now.
